apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: consul-reference-grant
  # namespace: default
  # namespace: demo
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: consul  # Must match the namespace that api-gw/routes.yaml is deployed into
  to:
    - group: ""
      kind: Service

# This enables an HTTPRoute in consul "namespace" (api-gw/routes.yaml)
# to point at a backend in a different namespace, e.g., demo/nginx.