---
apiVersion: v1
kind: Namespace
metadata:
  name: debug
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: debug
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: debug
spec:
  selector:
    app: debug
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: debug
spec:
  protocol: "http"