apiVersion: v1
kind: Pod
metadata:
  name: debug
  # namespace: debug
  namespace: demo
  labels:
    app: debug
    service: debug
  annotations:
    consul.hashicorp.com/connect-inject: "true"
    # Enable this if you want to use upstreams
    # from this pod:
    #   curl -sS http://127.0.0.1:8080/
    #   curl -sS http://127.0.0.1:3000/
    # NOTE: normal k8s service requests will not work, e.g.
    #   curl frontend.demo.svc.cluster.local:3000 - curl: (52) Empty reply from server
    #   curl frontend.demo:3000                   - curl: (52) Empty reply from server
    # consul.hashicorp.com/connect-service-upstreams: "public-api:8080,frontend:3000"
spec:
  serviceAccountName: debug
  containers:
    - name: netshoot
      image: nicolaka/netshoot
      command: ["sleep","3600"]