apiVersion: v1
kind: Pod
metadata:
  name: client
  annotations:
    consul.hashicorp.com/connect-inject: "false"
spec:
  containers:
    - name: netshoot
      image: nicolaka/netshoot
      command: ["sleep","3600"]